### ISSUE TITLE
Explain each button function

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/RDFPlayground#1]
The action performed for each button sometimes isn't clear (specially for newcomers), My initial idea is to add a `title` to each button on the frontend.

**Comment by Dave-mash** [comment]
@BastyZ How about a tooltip? I'd love to help out on this

**Comment by BastyZ** [comment]
A tooltip would be great! the frontend uses VuetifyJs, so this [tooltip documentation](https://vuetifyjs.com/en/components/tooltips/#props) should be used as guide :D

**Comment by Dave-mash** [comment]
> A tooltip would be great! the frontend uses VuetifyJs, so this [tooltip documentation](https://vuetifyjs.com/en/components/tooltips/#props) should be used as guide :D

https://github.com/BastyZ/RDFPlayground/pull/2

**Comment by Dave-mash** [comment]
Hi, would you mind adding a hacktoberfest-accepted label to my pull request please..
